# -*- coding: utf-8 -*-
"""pp3_introduction_to_the_Pandas_Library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sycu-LI1RTMycBzRQ58BalBajJIHF_-y

# **Python para análise de dados(Pandas)** - *Fernanda Santos*
"""

# análise de dados de uma planilha contendo dados como Pais, continente, Ano, Expectativa de vida, População Total, e PIB per capita.
# Usando Pandas é possível extrair informações como a expectativa de vida média para cada ano, entre outras informações.
from google.colab import drive
drive.mount('/content/drive')

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/My Drive/Datasets/Gapminder.csv",error_bad_lines=False, sep=";")

#Visualizando as 5 primeiras linhas
df.head()

df = df.rename(columns={"country":"Pais", "continent": "continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap": "PIB"})

df.head(10)

#Total de linhas e colunas
df.shape

df.columns

df.dtypes

df.tail(15)

df.describe()

df["continente"].unique()

Oceania = df.loc[df["continente"] == "Oceania"]
Oceania.head()

Oceania["continente"].unique()

# total de países por continente
df.groupby("continente")["Pais"].nunique()

# expectativa de vida média para cada ano
df.groupby("Ano")["Expectativa de vida"].mean()

df["PIB"].mean()

df["PIB"].sum()

